// Generated from halide_scratch/autonomous_build_config.json (plus a run section)
// so stories show a realistic config: 3 pumps, 3 phases, xray evaluation.
export const mockConfig: Record<string, any> = {
    connection: {
        queue_server: true,
        http_server_uri: 'https://xf28id2-xpd-qs1.nsls2.bnl.gov',
        zmq_consumer_address: 'ipc:///var/lib/bluesky-zmq-proxy/xpd-ipc-in-ipc-out/out.sock',
        tiled_profile: 'xpd',
        tiled_uri: null,
        sandbox_uri: 'https://tiled.nsls2.bnl.gov',
    },
    evaluation_method: 'xray',
    pdf_mode: 'raw',
    agent_data_path: null,
    checkpoint_path: null,
    metadata: {
        beamline: '28id2',
        tags: ['qserver', 'bluesky'],
        comment: 'Halide Synthesis Test',
    },
    success_criteria: null,
    pumps: [
        {
            name: 'CsPb',
            id: 'dds2_p1',
            bounds: [10, 200],
            parameter_type: 'float',
        },
        {
            name: 'Br',
            id: 'dds2_p2',
            bounds: [5, 200],
            parameter_type: 'float',
        },
        {
            name: 'I2',
            id: 'dds3_p1',
            bounds: [0, 200],
            parameter_type: 'float',
        },
    ],
    experiment: {
        sources: [
            {
                dof: 'infusion_rate_CsPb',
                pump: 'dds2_p1',
                precursor: 'CsPbOA',
                sample_label: 'CsPb',
                syringe_ml: 50.0,
                material: 'steel',
                target_ml: 30.0,
                set_target: true,
            },
            {
                dof: 'infusion_rate_Br',
                pump: 'dds2_p2',
                precursor: 'TOABr',
                sample_label: 'Br',
                syringe_ml: 50.0,
                material: 'steel',
                target_ml: 30.0,
                set_target: true,
            },
            {
                dof: 'infusion_rate_I2',
                pump: 'dds3_p1',
                precursor: 'ZnI2',
                sample_label: 'I2',
                syringe_ml: 50.0,
                material: 'steel',
                target_ml: 30.0,
                set_target: true,
            },
        ],
        dilutions: [
            {
                pump: 'dds1_p1',
                ratio: 1.0,
                position: 'before_equilibrium',
                syringe_ml: 20,
                material: 'plastic_BD',
                target_ml: 20,
                set_target: true,
                wait_sec: 0.0,
            },
            {
                pump: 'ultra2',
                ratio: 1.0,
                position: 'after_equilibrium',
                syringe_ml: 100,
                material: 'steel',
                target_ml: 100,
                set_target: true,
                wait_sec: 30,
            },
        ],
        wash_cycles: [
            {
                pump: 'ultra1',
                rate_ul_min: 500.0,
                duration_sec: 60.0,
                syringe_ml: 50.0,
                material: 'steel',
                target_ml: 30.0,
                set_target: false,
            },
        ],
    },
    xray: {
        max_retries: 10,
        retry_delay: 2.0,
        settings: {
            exposure: 600.0,
            frame_acq_time: 1.5,
            no_dark: false,
            stream_name: 'scattering',
        },
        screening: 'screen_and_record',
        quality_policy: {
            enabled: true,
            good_batches: 2,
            max_bad_batches: 3,
            absorbance_shots: 16,
            fluorescence_shots: 16,
        },
        objective_function: 'pearson',
        min_radius: 2.0,
        max_radius: 20.0,
        phases: [
            {
                name: 'CsPbBr3',
                gr: 'refdata/CsPbBr3.gr',
                cif: 'refdata/CsPbBr3.cif',
                simulated: false,
                minimize: false,
            },
            {
                name: 'CsBr',
                gr: 'refdata/CsBr.gr',
                cif: 'refdata/CsBr.cif',
                simulated: false,
                minimize: true,
            },
            {
                name: 'Cs4PbBr6',
                gr: 'refdata/Cs4PbBr6.gr',
                cif: 'refdata/Cs4PbBr6.cif',
                simulated: false,
                minimize: true,
            },
        ],
    },
    uvvis: {
        peak_target: 450,
        peak_tolerance: 5,
        max_retries: 10,
        retry_delay: 2.0,
        fit_settings: {
            pl_screen_key_height: 200,
            pl_screen_peak_height: 50,
            pl_screen_peak_distance: 100,
            pl_percent_range: [40, 100],
            pl_wavelength_range: [400, 800],
            pl_fit_maxfev: 100000,
            pl_fit_r2_window_sigma: 3,
            absorbance_percent_range: [10, 70],
            absorbance_wavelength_range: [210, 700],
        },
        plqy: {
            reference_type: 'quinine',
            excitation_wavelength_nm: 365,
            absorbance: 0.361,
            pl_integral: 952628,
            refractive_index: 1.337,
            plqy: 0.546,
            solvent_refractive_index: 1.506,
        },
    },
    run: {
        iterations: 40,
        n_points: 1,
        generation_strategy: {},
        local: {
            mixer_lengths_cm: [0.0],
            residence_time_ratio: 0.0,
            simulated: null,
        },
    },
};
